### PR TITLE
Proposal: reduce size of docker images

### PR DESCRIPTION
**Pull request by aledbf**
This PR reduce the size of the docker images up to a ~40% doing:
- change base image to [gcr.io/google_containers/ubuntu-slim:0.5](https://github.com/kubernetes/contrib/tree/master/images/ubuntu-slim)
- standarize RUN commands
- use xenial instead of trusty
- cleanup of deb packages after installation
- remove golang from images
- update package versions
- make sure sws is running
- remove go get from images

### CODE REVIEW

**Comment by VictorLowther** [comment]
This looks good to me -- I will test it locally.

**Comment by VictorLowther** [comment]
Please don't include the built .deb files -- we have a policy of not including build artifacts like these in the git repo.

**Comment by VictorLowther** [comment]
I folded these changes along with a few others to make the a deploy work using these containers.

**Comment by aledbf** [comment]
@VictorLowther awesome. I'm sorry for the delay to make the requested change

**Comment by VictorLowther** [comment]
No worries -- I have had vague plans to rebase our containers on alpine, but it has never been high enough priority to actually get done.

**Pull request closed without merging**
